# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e359653a0de112fee74736f6d137bbe7f0dd4978537fd867dbd8781cd7834ad71abdc877acfd4e50540b214e50da0df1f629a7faa7ab418cbb1dc5a0f7c8eaea

test:
  secret_key_base: 0515b8e19adaee164d946517379033db99da6fd84feb9a6c2e7913ad499b504f3b2f123e439a84d3b0b41f4338e99a05618d5129d81af2a646e6e1ff490eeef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
